### ISSUE TITLE
Quote price is not shown to the user

### ISSUE THREAD

**Issue by seurdge** [olidenis/Rocket_Elevators_Information_System#47]
<img width="1110" alt="Screen Shot 2019-03-10 at 4 57 10 PM" src="https://user-images.githubusercontent.com/82583/54091350-99047c80-4355-11e9-943a-7427ece4d0bf.png">

**Comment by olidenis** [comment]
We asked Mathieu LeFrancois about this and he said the the price should not be shown to the user?

**Comment by seurdge** [comment]
Ok I’ll beat the shit out of him tomorrow

**Comment by olidenis** [comment]
Lol :)
Our question was exactly that, should we show the price to the user or just add it in the quote. He said yeah usually that what the quote is for, you dont show the price yet, and you contact the clients and negociate that price. etc etc.

**Comment by seurdge** [comment]
Anyway, no points involved :-)

**Comment by olidenis** [comment]
Alright! Still good to know though! ;)
